### ISSUE TITLE
Documentation: jQuery interface both prefixes and _lowercases_ FileDrop events.

### ISSUE THREAD

**Issue by rpavlik** [ProgerXP/FileDrop#40]
Had trouble figuring out how to get `dragEnter`/`dragLeave` using the jQuery integration till I dug into the source, and noticed that the event name is being lowercased in addition to having the `fd` or `file` prefix attached. I didn't see this in the docs anywhere.

**Comment by ProgerXP** [comment]
Indeed, added this explicitly to the docs. Thanks for reporting.
