### ISSUE TITLE
node.js / npmjs.org publication?

### ISSUE THREAD

**Issue by Pomax** [ProgerXP/FileDrop#41]
If possible, can this library be made nodejs-flavour commonjs compatible and published to npm, so that we can do `npm install filedrop --save` and write a million things that need drag-and-drop file handling? It would make the life of an automation engineer a *lot* easier =D

**Comment by ProgerXP** [comment]
What tells you that FileDrop isn't on npm already?

https://www.npmjs.com/package/filedrop

**Comment by Pomax** [comment]
mostly the fact that it doesn't have a package.json in the main dir, which is supposed to be a requirement for doing an `npm publish`. Bower's not as useful, since it's much harder to use in automation setups (great if you do only client-side work, not so great if you have automated build setups)

**Comment by ProgerXP** [comment]
> mostly the fact that it doesn't have a `package.json` in the main dir

Oh. Sorry, it turned out that I forgot to push the changes I've made a while ago. Now it's here. Doesn't change the fact that FileDrop's on npm already though.

**Comment by Pomax** [comment]
nice!
