### ISSUE TITLE
Please use a real software license

### ISSUE THREAD

**Issue by mordocai** [ProgerXP/FileDrop#58]
Google around, there is a lot of confusion on whether in certain countries it is even possible to release something into the public domain yourself.

It would be very helpful if you could just release the software under a standard permissive license. My company is worried about using this library due to the ambiguity. Since you are the only contributor, this should not be a problem from that perspective.

**Comment by ProgerXP** [comment]
Yeah, and what about SQLite?

> SQLite is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine. SQLite is the most widely deployed database engine in the world. The source code for SQLite is in the public domain. 

If companies like Mozilla managed to find their way around, your company should have no problem too.

FileDrop can be as well released under http://unlicense.org.
