### ISSUE TITLE
move_uploaded_file

### ISSUE THREAD

**Issue by moscorp** [ProgerXP/FileDrop#78]
hi, can I have a example that actual move the file into server?!
Thanks,

**Comment by ProgerXP** [comment]
See upload.php/upload.aspx for examples.

**Comment by moscorp** [comment]
Hello,

I can upload the file throught ie by adding 
move_uploaded_file($_FILES['fd-file']['tmp_name'],....
and it can run also in chrome at the beginning only for serveral time,,, 
even I reboot the pc, its doesn't work anymore, but still works in ie.
Seems it can't catch the file name,, is any restriction on Chrome?



------ Original Message ------

**Comment by moscorp** [comment]
Hello,

Sorry, I found the error. It is because chrome doesn't support the 
following statement,, do you have any idea to solve it?!

$acceptedext = 
array("pdf","csv","xls","xlsx","doc","docx","jpg","tif","png","ppt","rar","zip");
$ext = strtolower(pathinfo($oldFilename, PATHINFO_EXTENSION));
if (!in_array($ext, $acceptedext)) {

------ Original Message ------
From: "Melvin" ***@***.***>
To: "ProgerXP/FileDrop" 
***@***.***>; 
"ProgerXP/FileDrop" ***@***.***>
Cc: "Author" ***@***.***>
Sent: 2021-05-06 3:06:09 PM
Subject: Re[2]: [ProgerXP/FileDrop] move_uploaded_file (#78)

Hello,

I can upload the file throught ie by adding 
move_uploaded_file($_FILES['fd-file']['tmp_name'],....
and it can run also in chrome at the beginning only for serveral time,,, 
even I reboot the pc, its doesn't work anymore, but still works in ie.
Seems it can't catch the file name,, is any restriction on Chrome?



------ Original Message ------
