### ISSUE TITLE
MIME type before upload?

### ISSUE THREAD

**Issue by moscorp** [ProgerXP/FileDrop#79]
how to restrict MIME type before upload?!

**Comment by ProgerXP** [comment]
See examples in filedropjs.org. MIME type is accessible via [File.type](https://filedropjs.org/#file). Or, on the server-side, use PHP's `$_FILES['upload']['type']` or `mime_content_type()`.

However, MIME checks are generally unreliable both client- and server-side. It's better to check file's actual contents using Fileinfo (PHP), gd, etc..
